In [2]:
import numpy as np

In [3]:
n = np.array([[1,5,6,3], [7,4,8,9], [4,1,2,7]])

In [3]:
n

array([[1, 5, 6, 3],
       [7, 4, 8, 9],
       [4, 1, 2, 7]])

In [5]:
n.shape

(3, 4)

In [6]:
n[0][0]

1

In [7]:
n[2,1:3]

array([1, 2])

In [8]:
n[1:3,2:4]

array([[8, 9],
       [2, 7]])

In [4]:
n[0:4,3]

array([3, 9, 7])

In [5]:
list(range(5,51))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [6]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [10]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a = np.arange(12).reshape(3,4)

In [12]:
a.max()

11

In [13]:
a.min()

0

In [14]:
a.argmax()

11

In [15]:
np.random.rand(2,2)

array([[0.60757007, 0.50981203],
       [0.20377246, 0.67613748]])

In [16]:
np.random.randn(2,2)

array([[-0.0244126 ,  0.80252498],
       [-1.44362101, -0.77905136]])

In [17]:
np.random.randint(9,90,12)

array([87, 12, 58, 25, 35, 25, 83, 67, 89, 40, 72, 87])

In [19]:
np.random.randint(9,90,12).reshape(6,2)

array([[59, 60],
       [70, 76],
       [27, 23],
       [58, 30],
       [42, 69],
       [81, 81]])

In [21]:
s = np.random.randint(9,90,12).reshape(6,2)

In [22]:
s.sum()

586

In [24]:
s

array([[23, 38],
       [28, 72],
       [87, 82],
       [50, 20],
       [45, 16],
       [39, 86]])

In [23]:
s.sum(axis=1)

array([ 61, 100, 169,  70,  61, 125])